modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="registrate"
version="${file.jarVersion}"
displayName="Registrate"
authors="tterrag"
description='''
Dummy mod for Registrate in userdev
'''